server:
  pid: testdata/
  name: server_test
  addr: 0.0.0.0:12349
  shutdown_wait_duration: 30s
  gin_mode: release
  metrics: metrics

captcha:
  driver:
    captcha_type: string
    length: 6
    height: 120
    width: 400
    noise_count: 10
    show_line_options: 8
    source: "qwertyupasfghjkmnbvcxz123456789"
  store:
    redis_type: default
    addrs:
      - 127.0.0.1:6379
    password:
    db: 5
    pool_size: 5000
    min_idle_conns: 100

database:
  master:
    log_level: info
    dsn: root@(localhost:3306)/crane?charset=utf8&parseTime=True&loc=Local
    max_idle: 20
    max_open: 100
    replicas:
      max_idle: 20
      max_open: 100
      connections:
        - root@(localhost:3306)/crane?charset=utf8&parseTime=True&loc=Local

logger:
  max_age: 720h
  rotation_time: 1s
  level: trace
  path: testdata/
  report_caller: true

password:
  token: 123456
  cost: 10

redis:
  redis_type: default
  addr: 127.0.0.1:6379
  password:
  db: 5
  pool_size: 5000
  min_idle_conns: 100

sessions:
  driver: redis
  key: 123456
  name: GOSID
  domain: localhost
  max_age: 2h
  http_only: true
  redis:
    redis_type: default
    addr: 127.0.0.1:6379
    password:
    db: 6
    pool_size: 5000
    min_idle_conns: 100
